name: build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9"]

    steps:
    - uses: actions/checkout@v3  
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt-get update -qq
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest coveralls
        pip install -r requirements.txt
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: install package
      run: |
        pip install .
        pip list
    
    - name: Lint with flake8
      run: |
        flake8 .
      continue-on-error: true  
    - name: Test with pytest
      run: |
        pip install pytest
        pip install pytest-cov
        pip install coveralls
        coverage run --source=ffta -m pytest tests/
    
    - name: Publish to coveralls.io
      uses: coverallsapp/github-action@v1.1.2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: coverage.xml


    - name: Publish distribution
      if: startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
